import type { Metadata } from 'next';
import { Host_Grotesk } from 'next/font/google';
import './globals.css';

const grotesk = Host_Grotesk({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: {
        template: 'Puzzle game %s',
        default: 'Puzzle game',
    },
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${grotesk.className} bg-zinc-800 text-gray-100 antialiased`}>
                <main className='container mx-auto flex flex-col justify-center items-center gap-4 h-dvh'>
                    {children}
                </main>
            </body>
        </html>
    );
}
